stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DEBIAN_FRONTEND: noninteractive


.run-tests-template: &run-tests-template
  script:
    - pipenv shell
    - python tests/runtests.py \
          -C \
          -r \
          tests/[0-9]*

test:
  stage: test
  dependencies:
  <<: *run-tests-template
