stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DEBIAN_FRONTEND: noninteractive


.run-tests-template: &run-tests-template
  script:
    - pipenv run python tests/runtests.py \
          -C \
          -r \
          -b {} \
          tests/[0-9]*

test:
  image: python:3.9.0
  stage: test
  before_script:
    - apt-get update
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install pipenv
    - PIPENV_VENV_IN_PROJECT=1
    - pipenv --python $(which python)
  dependencies:
  <<: *run-tests-template
