stages:
  - analyze
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DEBIAN_FRONTEND: noninteractive


analyze:
  image: ubuntu:bionic
  stage: analyze
  before_script:
    - apt-get update
    - apt-get install -y pandoc
    - apt-get install -y python3
    - apt-get install -y python3-pip
    - pip3 install black==20.8b1
    - pip3 install mypy
  script:
    - python3 -m mypy sbg.py sbg_functions.py mssrc.py evaluate.py velocity_tsa.py tools/globals.py tools/TestRunner.py tools/TestDefinition.py dataio/H5Base.py dataio/H5Reader.py dataio/H5Writer.py --ignore-missing-imports --check-untyped-defs --python-version 3.9
    - python3 -m black --check sbg.py sbg_functions.py mssrc.py evaluate.py velocity_tsa.py tools/globals.py tools/TestRunner.py tools/TestDefinition.py dataio/H5Base.py dataio/H5Reader.py dataio/H5Writer.py --ignore-missing-imports --check-untyped-defs --python-version 3.9

.run-tests-template: &run-tests-template
  script:
    - pipenv run python tests/runtests.py -Cr tests/[0-9]*

test:
  image: python:3.9.0
  stage: test
  before_script:
    - apt-get update
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install pipenv
    - PIPENV_VENV_IN_PROJECT=1
    - pipenv --python $(which python)
    - pipenv install --ignore-pipfile
  dependencies:
  <<: *run-tests-template
